name: sports

channels:
 - conda-forge
 
dependencies:
- python
- arviz
- ipython
- jax
- jaxlib
- jupyterlab
- notebook
- ipykernel
- numpy
- numpyro
- pandas
- patsy
- pip
- polars
- preliz
- pyarrow
- python-graphviz
- pymc
- scipy
- seaborn
- pip:
  - pybaseball
