name: pymc_sports_analytics

channels:
 - conda-forge
 
dependencies:
- python
- arviz
- ipython
- jax
- jaxlib
- jupyterlab
- notebook
- ipykernel
- numpy
- numpyro
- pandas
- patsy
- pip
- python-graphviz
- pymc
- scipy
- seaborn
